-- MySQL Script generated by MySQL Workbench
-- Thu Mar 19 20:13:19 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema opentickets_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema opentickets_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `opentickets_db` DEFAULT CHARACTER SET utf8 ;
USE `opentickets_db` ;

-- -----------------------------------------------------
-- Table `opentickets_db`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `opentickets_db`.`User` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(256) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `access_level` ENUM('Admin', 'L1', 'L2', 'User') NOT NULL DEFAULT 'User',
  `first_name` VARCHAR(100) NOT NULL,
  `last_name` VARCHAR(100) NOT NULL,
  `last_login` TIMESTAMP NULL DEFAULT NULL,
  `force_password_change` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `opentickets_db`.`ActiveTickets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `opentickets_db`.`ActiveTickets` (
  `ticket_number` BINARY(16) NOT NULL,
  `created_by` INT NOT NULL,
  `ticket_name` VARCHAR(300) NOT NULL,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `status_code` ENUM("O", "C", "E", "R", "P") NOT NULL DEFAULT 'O',
  `contains_flagged_url` TINYINT NOT NULL DEFAULT 0,
  `priority_code` ENUM("L", "M", "H", "C") NOT NULL DEFAULT 'H',
  `ticket_description` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`ticket_number`),
  INDEX `userid_idx` (`created_by` ASC) VISIBLE,
  INDEX `StatusCode_idx` (`status_code` ASC) VISIBLE,
  INDEX `PriorityCode_idx` (`priority_code` ASC) VISIBLE,
  CONSTRAINT `a_t_user_id_fk`
    FOREIGN KEY (`created_by`)
    REFERENCES `opentickets_db`.`User` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `opentickets_db`.`Sessions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `opentickets_db`.`Sessions` (
  `session_id` BINARY(16) NOT NULL,
  `user_id` INT NOT NULL,
  `session_token` VARCHAR(512) NOT NULL,
  `created_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `expire_time` TIMESTAMP NOT NULL,
  `ip_address` VARCHAR(164) NULL,
  `user_agent_header` VARCHAR(512) NULL,
  `is_valid` BINARY(1) NULL DEFAULT 1,
  INDEX `UserID_idx` (`user_id` ASC) VISIBLE,
  PRIMARY KEY (`session_id`),
  CONSTRAINT `s_user_id_fk`
    FOREIGN KEY (`user_id`)
    REFERENCES `opentickets_db`.`User` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `opentickets_db`.`TicketComments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `opentickets_db`.`TicketComments` (
  `comment_number` BINARY(16) NOT NULL,
  `ticket_number` BINARY(16) NOT NULL,
  `created_by` INT NOT NULL,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `comment_description` MEDIUMTEXT NOT NULL,
  `contains_flagged_url` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`comment_number`),
  INDEX `createdby_idx` (`created_by` ASC) VISIBLE,
  INDEX `TicketNumberx` (`ticket_number` ASC) VISIBLE,
  CONSTRAINT `t_c_ticket_number_fk`
    FOREIGN KEY (`ticket_number`)
    REFERENCES `opentickets_db`.`ActiveTickets` (`ticket_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `t_c_user_id_fk`
    FOREIGN KEY (`created_by`)
    REFERENCES `opentickets_db`.`User` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `opentickets_db`.`TicketAttachments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `opentickets_db`.`TicketAttachments` (
  `attachment_id` BINARY(16) NOT NULL,
  `comment_number` BINARY(16) NOT NULL,
  `created_by` INT NOT NULL,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `attachment_path` VARCHAR(1024) NOT NULL,
  `attachment_name` VARCHAR(255) NOT NULL,
  `md5_checksum` BINARY(16) NOT NULL,
  `attachment_type` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`attachment_id`),
  INDEX `CommentNumber_idx` (`comment_number` ASC) VISIBLE,
  INDEX `UserID_idx` (`created_by` ASC) VISIBLE,
  CONSTRAINT `t_a_comment_number_fk`
    FOREIGN KEY (`comment_number`)
    REFERENCES `opentickets_db`.`TicketComments` (`comment_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `t_a_user_id_fk`
    FOREIGN KEY (`created_by`)
    REFERENCES `opentickets_db`.`User` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- TEMPORARY: Insert test admin account for development/testing
INSERT IGNORE INTO `opentickets_db`.`User` (
  `email`, 
  `password`, 
  `access_level`, 
  `first_name`, 
  `last_name`, 
  `force_password_change`
) VALUES (
  'admin@example.com',
  '$argon2id$v=19$m=65536,t=3,p=4$epZ8q95eL8AZNszOjBzcBA$Dchueac1nY9268lTDgTHbBN6yWfzUYE6oD3OfbMIWgE',
  'Admin',
  'Admin',
  'User',
  0
);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;